export default {
  name: "autogiro",
  type: "document",
  title: "Autogiro payment method",
  fields: [
    {
      name: "selector_text",
      title: "Selector text",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "account_number_label",
      title: "Account number label",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "account_number",
      title: "Account number",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "payer_number_label",
      title: "Payer number label",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "manual_recurring_option_config",
      title: "Manual recurring option config",
      type: "object",
      fields: [
        {
          name: "title",
          title: "Title",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "sum_label",
          title: "Sum label",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "payer_numberexplanatory_text",
          title: "Payer number explanatory text",
          type: "text",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "instruction_text",
          title: "Instruction text",
          type: "array",
          of: [{ type: "block" }],
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "complete_button_text",
          title: "Complete button text",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
      ],
    },
    {
      name: "recurring_manual_option_config",
      title: "Recurring manual option config",
      type: "object",
      fields: [
        {
          name: "title",
          title: "Title",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "explanation_text",
          title: "Explanation text",
          type: "array",
          of: [{ type: "block" }],
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "date_selector_config",
          title: "Date selector config",
          type: "reference",
          to: [{ type: "dateselectorconfig" }],
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "complete_button_text",
          title: "Complete button text",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
      ],
    },
    {
      name: "recurring_form_option_config",
      title: "Recurring form option config",
      type: "object",
      fields: [
        {
          name: "title",
          title: "Title",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "explanation_text",
          title: "Explanation text",
          type: "array",
          of: [{ type: "block" }],
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "payernumber_label",
          title: "Payernumber label",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "button_text",
          title: "Button text",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: "button_link",
          title: "Button link",
          type: "string",
          validation: (Rule: any) => Rule.required(),
        },
      ],
    },
    {
      name: "completed_text",
      title: "Completed text",
      type: "array",
      of: [{ type: "block" }],
      validation: (Rule: any) => Rule.required(),
    },
  ],
};
