name: Feature request ✨
description: Request a new feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description 
      description: What is the intended change?
      placeholder: Tell us what you want to see!
      Tip: Framing this as a user story might be helpfull. E.g. [as a user I want to be able to get a readout of my yearly tax deductible donations, so that I feel confident that the correct amount is reported]
    validations:
      required: true
  - type: input
    id: figma-link
    attributes:
      labels: Link to figma / design node
      description: Select an element in Figma, click share (top right corner) and remember to check [link to selected frame]
    validations:
      required: false
  - type: input
    id: planning-document-link
    attributes:
      labels: Link to other planning document
      description: Link to relevant document from planning stage, f.ex. google doc, google sheets etc.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? References?

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
