import { useAuth0 } from "@auth0/auth0-react";
import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../../components/profile/layout";
import styles from "../../styles/Home.module.css";
import style from "../../styles/Profile.module.css";
import { LayoutPage } from "../../types";

const Home: LayoutPage = () => {
  const { logout, user } = useAuth0();
  return (
    <>
      <Head>
        <title>Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.gridContainer}>
        <h1 className={style.header}>Hei {user ? user["https://konduit.no/user-id"] : "..."}!</h1>
        <section className={style.personalInfo}>
          <hr />
          Ditt navn <br />
          <input type="text" value="Test Testesen"/> <br /> <br />
          E-post <br />
          <input type="email" disabled  value="hallo@hei.no"/> <br /> <br />
          Fødselsnummer / Organisasjonsnummer <br />
          <input type="number" value={34567890}/> <br /> <br />
          <input type="checkbox" checked/> Send meg nyhetsbrev på
          e-post <br />
          <br />
          <button>Lagre</button>
        </section>

        <section className={style.gridContainer2}>
          <section className={style.dataHeader}>
          <hr />
          <h2>Om dine data</h2>
          </section>
          <section className={style.taxSection}>
            <h3>Skattefradrag</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id dictum lectus, 
              sit amet ultricies metus. Pellentesque condimentum tortor commodo, laoreet ex sit 
              amet, auctor nisi. Orci varius natoque penatibus et magnis dis parturient montes, 
              nascetur ridiculus mus. Phasellus ut risus vel dui vestibulum semper ut ac lorem. 
              Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ultricies magna 
              non finibus tincidunt. Aliquam tincidunt accumsan ligula vitae faucibus. Duis leo 
              leo, sodales et elit eget, varius rhoncus quam. Maecenas porta efficitur lectus non 
              eleifend. Donec eu auctor mauris, vitae facilisis augue. Proin maximus, sem at placerat 
              tristique, lorem.</p>
          </section>
          <section className={style.privacySection}>
            <h3>Personvern</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id dictum lectus, 
              sit amet ultricies metus. Pellentesque condimentum tortor commodo, laoreet ex sit 
              amet, auctor nisi. Orci varius natoque penatibus et magnis dis parturient montes, 
              nascetur ridiculus mus. Phasellus ut risus vel dui vestibulum semper ut ac lorem. 
              Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ultricies magna 
              non finibus tincidunt. Aliquam tincidunt accumsan ligula vitae faucibus. Duis leo 
              leo, sodales et elit eget, varius rhoncus quam. Maecenas porta efficitur lectus non 
              eleifend. Donec eu auctor mauris, vitae facilisis augue. Proin maximus, sem at placerat 
              tristique, lorem.</p>
          </section>
        </section>
      </div>
    </>
  );
};
Home.layout = Layout;
export default Home;
