import { useAuth0 } from "@auth0/auth0-react";
import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../../components/profile/layout";
import styles from "../../styles/Home.module.css";
import { LayoutPage } from "../../types";

const Home: LayoutPage = () => {
  const { logout, user } = useAuth0();
  return (
    <>
      <Head>
        <title>Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="profilePageContainer">
        <h1>Hei {user ? user["https://konduit.no/user-id"] : "..."}!</h1>
        <section id="personalInformation">
          <hr />
          Ditt navn <br />
          <input type="text" id="nameInput" /> <br /> <br />
          E-post <br />
          <input type="email" id="emailInput" disabled /> <br /> <br />
          Fødselsnummer / Organisasjonsnummer <br />
          <input type="number" id="ssnInput" /> <br /> <br />
          <input type="checkbox" id="newsletterInput" /> Send meg nyhetsbrev på
          e-post <br />
          <br />
          <button>Lagre</button>
        </section>

        <section id="yourData">
          <hr />
          <h2>Om dine data</h2>
          <section>
            <h3>Skattefradrag</h3>
            <p>Lorem ispum</p>
          </section>
          <section>
            <h3>Personvern</h3>
            <p>Lorem ispum</p>
          </section>
        </section>
      </div>
    </>
  );
};
Home.layout = Layout;
export default Home;
