import { useAuth0 } from '@auth0/auth0-react'
import { resolveSoa } from 'dns'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import DonationsChart from '../../components/charts/donations'
import { Layout } from '../../components/profile/layout'
import { useApi } from '../../hooks/useApi'
import { AggregatedDonations, DonationGraphData } from '../../models'
import { LayoutPage } from '../../types'

const Home: LayoutPage = () => {
  const { getAccessTokenSilently, user } = useAuth0();
  const [graphData, setGraphData] = useState<null | any[]>(null);

  useApi<AggregatedDonations[]>(
    `/donors/${user ? user["https://konduit.no/user-id"] : ""}/donations/aggregated`,
    "GET",
    "read:donations",
    getAccessTokenSilently,
    (res) => {
      let data: any[] = []
      res = res.sort((a, b) => b.year - a.year)
      for (let i = 0; i < res.length; i++) {
        if (i == 0 || (data[data.length-1].name != res[i].year)) {
          let obj: any = {}

          obj["name"] = res[i].year
          obj[res[i].organization] = parseFloat(res[i].value)

          data.push(obj)
        } else {
          data[data.length-1][res[i].organization] = parseFloat(res[i].value)
        }
      }
      console.log(data)
      setGraphData(data)
    }
  );

  if (!graphData)
    return <></>

  return (
    <>
      <Head>
        <title>Konduit. - Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Donasjoner</h1>

      <div style={{ height: 450 }}>
        <DonationsChart data={graphData} />
      </div>
      {/* <Donations /> */}
    </>
  )
}
Home.layout = Layout
export default Home
