import Head from "next/head";
import { Layout } from "../../components/profile/layout/layout";
import { DataInfo } from "../../components/profile/details/DataInfo/DataInfo";
import style from "../../styles/Profile.module.css";
import { LayoutPage } from "../../types";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/router";
import { getClient } from "../../lib/sanity.server";
import { groq } from "next-sanity";
import { PageContent } from "../../components/profile/layout/PageContent/PageContent";
import { Navbar } from "../../components/profile/layout/navbar";
import { ProfileInfo } from "../../components/profile/details/ProfileInfo/ProfileInfo";
import { footerQuery } from "../../components/shared/layout/Footer/Footer";
import { MainHeader } from "../../components/shared/layout/Header/Header";
import { FacebookTaxWidget } from "../../components/profile/tax/FacebookTaxWidget/FacebookTaxWidget";

const Home: LayoutPage<{ data: any; preview: boolean }> = ({ data, preview }) => {
  const router = useRouter();
  const settings = data.result.settings[0];

  if (!router.isFallback && !data) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Gi Effektivt. | Skatt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader hideOnScroll={false}>
        <Navbar logo={settings.logo} />
      </MainHeader>

      <PageContent>
        <h3 className={style.header}>Skatt</h3>
        <div className={style.gridContainer}>
          <section>
            <h5>Registrer Facebook-donasjoner for skattefradrag</h5>
            <FacebookTaxWidget />
          </section>
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ preview = false }) {
  const result = await getClient(preview).fetch(fetchProfilePage);

  return {
    props: {
      preview: preview,
      data: {
        result: result,
        query: fetchProfilePage,
        queryParams: {},
      },
    },
  };
}

const fetchProfilePage = groq`
{
  "settings": *[_type == "site_settings"] {
    logo,
  },
  "page": *[_type == "profile"] {
    tax,
    data
  },
  ${footerQuery}
}
`;

Home.layout = Layout;
export default Home;
