import Head from "next/head";
import { Layout } from "../../components/profile/layout/layout";
import style from "../../styles/Tax.module.css";
import { LayoutPage } from "../../types";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/router";
import { getClient } from "../../lib/sanity.server";
import { groq } from "next-sanity";
import { PageContent } from "../../components/profile/layout/PageContent/PageContent";
import { Navbar } from "../../components/profile/layout/navbar";
import { footerQuery } from "../../components/shared/layout/Footer/Footer";
import { MainHeader } from "../../components/shared/layout/Header/Header";
import { FacebookTaxWidget } from "../../components/profile/tax/FacebookTaxWidget/FacebookTaxWidget";
import { useContext } from "react";
import { DonorContext } from "../../components/profile/layout/donorProvider";
import { PortableText } from "../../lib/sanity";
import Link from "next/link";
import { widgetQuery } from "../../_queries";

const Home: LayoutPage<{ data: any; preview: boolean }> = ({ data, preview }) => {
  const router = useRouter();
  const settings = data.result.settings[0];
  const { donor } = useContext(DonorContext);

  if (!router.isFallback && !data) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Gi Effektivt. | Skatt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader hideOnScroll={false}>
        <Navbar logo={settings.logo} />
      </MainHeader>

      <PageContent>
        <h3 className={style.header}>Skatt</h3>
        <div className={style.gridContainer}>
          <section>
            <h5>Facebook-donasjoner</h5>
            <FacebookTaxWidget
              name={donor ? donor.name : null}
              email={donor ? donor.email : null}
            />
          </section>
          <section>
            <h5>Skattefradrag</h5>
            <PortableText blocks={data.result.page[0].tax[0]} />

            <Link href="/skattefradrag" passHref>
              <a target={"_blank"}>Les mer →</a>
            </Link>
          </section>
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ preview = false }) {
  const result = await getClient(preview).fetch(fetchProfilePage);

  return {
    props: {
      preview: preview,
      data: {
        result: result,
        query: fetchProfilePage,
        queryParams: {},
      },
    },
  };
}

const fetchProfilePage = groq`
{
  "settings": *[_type == "site_settings"] {
    logo,
  },
  "page": *[_type == "profile"] {
    tax
  },
  ${footerQuery}
  ${widgetQuery}
}
`;

Home.layout = Layout;
export default Home;
