import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { PortableText } from "../lib/sanity";
import { getClient } from "../lib/sanity.server";
import styles from "../styles/Articles.module.css";
import { groq } from "next-sanity";
import { LayoutPage } from "../types";
import { Layout } from "../components/main/layout";
import { Navbar } from "../components/main/navbar";
import { PageHeader } from "../components/elements/pageheader";
import { SectionContainer } from "../components/sectionContainer";
import { Links } from "../components/elements/links";
import { EffektButton } from "../components/elements/effektbutton";

const Articles: LayoutPage<{ data: any; preview: boolean }> = ({ data, preview }) => {
  const settings = data.settings[0];

  return (
    <>
      <Head>
        <title>Konduit. - Artikler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar logo={settings.logo} elements={settings["main_navigation"]} />

      <PageHeader title={"Artikler."} custom__class={"grid"}>
        {/* <div className={`${styles.article__nav}`}> */}
        <section className={styles.search_field}>
          <input type="text" />
          <button>søk</button>
        </section>
        <div className={styles.article_filter}>
          <section>
            <a href="#">Alle Artikler</a>
            <a href="#">Nyheter</a>
            <a href="#">Dypdykk</a>
          </section>

          <section className={styles.article_filter__topic}>
            <a href="#">Global ulikhet</a>
            <a href="#">Organisajonene</a>
            <a href="#">Bistandsmyter</a>

            <a href="#">+</a>
          </section>
        </div>
        {/* </div> */}
      </PageHeader>

      <SectionContainer>
        <PortableText blocks={data.article}></PortableText>
      </SectionContainer>
    </>
  );
};

export async function getStaticProps({ preview = false }) {
  const data = await getClient(preview).fetch(fetchArticles);

  return {
    props: {
      preview,
      data,
    },
  };
}

const fetchArticles = groq`
{
  "settings": *[_type == "site_settings"] {
    logo,
    main_navigation[] {
      _type == 'navgroup' => {
        _type,
        _key,
        title,
        items[]->{
          title,
          "slug": page->slug.current
        },
      },
      _type != 'navgroup' => @ {
        _type,
        _key,
        title,
        "slug": page->slug.current
      },
    }
  },
  "article": *[_type == "article"] {
    header,
    content
  }
}
`;

Articles.layout = Layout;
export default Articles;
