import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import { getClient } from '../lib/sanity.server'
import { groq } from 'next-sanity'
import { LayoutPage } from '../types'
import { Layout } from '../components/main/layout'

const Method: LayoutPage<{ data: any; preview: boolean }> = ({
  data,
  preview,
}) => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Konduit. - Donations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Donations</h1>
    </>
  )
}

export async function getStaticProps({ preview = false }) {
  const data = await getClient(preview).fetch(fetchMethod)

  return {
    props: {
      preview,
      data,
    },
  }
}

const fetchMethod = groq`
{

}
`

Method.layout = Layout
export default Method
