import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/main/layout'
import { Stepwize } from '../components/stepwize/stepwize'
import { Testemonial } from '../components/testemonial'
import { SectionContainer } from '../components/sectionContainer'
import styles from '../styles/Home.module.css'
import { LayoutPage } from '../types'
import { Teaser } from '../components/elements/teaser'

const Home: LayoutPage = () => {
  return (
    <>
      <Head>
        <title>Konduit.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.hero}>
        <div className={styles.header}>
          <h1>Verdens mest effektivt bidrag.</h1>
        </div>
        <div className={styles.action}>
          Kostnadsfri videreformidling av donasjoner til de mest effektive
          tiltakene →
        </div>
      </div>
      <SectionContainer heading="Slik fungerer det">
        <Stepwize />
      </SectionContainer>
      <SectionContainer heading=''>
        <div className={styles.teasers}>
          <Teaser title='Maks impact.' paragraph='asodk' link='https://google.com/' imageurl='https://cdn.sanity.io/images/zp7mbokg/production/G3i4emG6B8JnTmGoN0UjgAp8-300x450.jpg'></Teaser>
          <Teaser title='Full oversikt.' paragraph='asodk' link='https://google.com/' imageurl='https://cdn.sanity.io/images/zp7mbokg/production/G3i4emG6B8JnTmGoN0UjgAp8-300x450.jpg'></Teaser>
          <Teaser title='Skattefradrag.' paragraph='asodk' link='https://google.com' imageurl='https://cdn.sanity.io/images/zp7mbokg/production/G3i4emG6B8JnTmGoN0UjgAp8-300x450.jpg'></Teaser>
        </div>
      </SectionContainer>
      <SectionContainer heading="Hva folk sier om oss">
        <Testemonial
          quote="
        Fordi de mest effektive bistandstiltakene er 100 ganger så effektive som median-organisasjonen. Med Konduit får jeg maksimal uttelling for det jeg gir."
          quotee="Aksel Braanen Sterri"
          quoteeBackground="Filosof"
        />
      </SectionContainer>
    </>
  )
}

Home.layout = Layout
export default Home
