import Head from "next/head";
import "react-toastify/dist/ReactToastify.css";
import { AgreementList } from "../../components/profile/shared/lists/agreementList/AgreementList";
import { AvtaleGiroAgreement, Distribution, Organization, VippsAgreement } from "../../models";
import { useAuth0, User } from "@auth0/auth0-react";
import {
  useAgreementsDistributions,
  useAvtalegiroAgreements,
  useOrganizations,
  useTaxUnits,
  useVippsAgreements,
} from "../../_queries";
import { useContext, useState } from "react";
import { ActivityContext } from "../../components/profile/layout/activityProvider";
import { InfoBox } from "../../components/shared/components/Infobox/Infobox";
import { AlertTriangle, Clock } from "react-feather";
import AgreementsMenu from "../../components/profile/agreements/AgreementsMenu/AgreementsMenu";
import styles from "../../styles/Agreements.module.css";
import { PageContent } from "../../components/profile/layout/PageContent/PageContent";
import { getClient } from "../../lib/sanity.server";
import { groq } from "next-sanity";
import { Spinner } from "../../components/shared/components/Spinner/Spinner";
import { MainHeader } from "../../components/shared/layout/Header/Header";
import Link from "next/link";
import { DateTime } from "luxon";
import { useRouterContext } from "../../context/RouterContext";
import { GetStaticPropsContext } from "next";
import { withStaticProps } from "../../util/withStaticProps";
import { GeneralPageProps, LayoutType, getAppStaticProps } from "../_app.page";
import { ProfileLayout } from "../../components/profile/layout/layout";
import { Navbar } from "../../components/shared/components/Navbar/Navbar";

export async function getAgreementsPagePath() {
  const result = await getClient(false).fetch<FetchAgreementsPageResult>(fetchAgreementsPage);

  const dashboardSlug = result?.dashboard?.[0]?.dashboard_slug?.current;
  const agreementsSlug = result?.page?.[0]?.slug?.current;

  if (!dashboardSlug || !agreementsSlug) return null;

  return [dashboardSlug, agreementsSlug];
}

export const AgreementsPage = withStaticProps(
  async ({ preview = false }: GetStaticPropsContext<{ slug: string[] }>) => {
    const appStaticProps = await getAppStaticProps({ preview, layout: LayoutType.Profile });

    return {
      appStaticProps,
      preview: preview,
      navbarData: await Navbar.getStaticProps({ dashboard: true, preview }),
    }; // satisfies GeneralPageProps (requires next@13);;
  },
)(({ navbarData, preview }) => {
  const { articlesPagePath } = useRouterContext();
  const { getAccessTokenSilently, user } = useAuth0();
  const [selected, setSelected] = useState<"Aktive avtaler" | "Inaktive avtaler">("Aktive avtaler");

  const {
    loading: avtaleGiroLoading,
    data: avtaleGiro,
    isValidating: avtaleGiroRefreshing,
    error: avtaleGiroError,
  } = useAvtalegiroAgreements(user, getAccessTokenSilently);

  const {
    loading: vippsLoading,
    data: vipps,
    isValidating: vippsRefreshing,
    error: vippsError,
  } = useVippsAgreements(user, getAccessTokenSilently);

  const kids = new Set<string>();
  if (vipps && avtaleGiro)
    [
      ...vipps?.map((a: VippsAgreement) => a.KID),
      ...avtaleGiro?.map((a: AvtaleGiroAgreement) => a.KID),
    ].map((kid) => kids.add(kid));

  const {
    loading: distributionsLoading,
    data: distributions,
    isValidating: distributionsRefreshing,
    error: distributionsError,
  } = useAgreementsDistributions(
    user,
    getAccessTokenSilently,
    !vippsLoading && !avtaleGiroLoading,
    Array.from(kids),
  );

  const {
    loading: taxUnitsLoading,
    data: taxUnits,
    isValidating: taxUnitsRefreshing,
    error: taxUnitsError,
  } = useTaxUnits(user, getAccessTokenSilently);

  const loading = vippsLoading || avtaleGiroLoading || distributionsLoading || taxUnitsLoading;

  if (loading || !distributions || !vipps || !avtaleGiro || !taxUnits)
    return (
      <>
        <Head>
          <title>Gi Effektivt. | Avtaler</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MainHeader hideOnScroll={false}>
          <Navbar {...navbarData} />
          <AgreementsMenu
            selected={selected}
            onChange={(selected) => setSelected(selected)}
          ></AgreementsMenu>
        </MainHeader>

        <PageContent>
          <div className={styles.container}>
            <h3 className={styles.header}>Faste avtaler</h3>
            <div style={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
              <Spinner />
            </div>
          </div>
        </PageContent>
      </>
    );

  const activeAvtalegiroAgreements: AvtaleGiroAgreement[] = avtaleGiro.filter(
    (agreement: AvtaleGiroAgreement) => agreement.active === 1,
  );

  const activeVippsAgreements: VippsAgreement[] = vipps.filter(
    (agreement: VippsAgreement) => agreement.status === "ACTIVE",
  );

  // A map with kid as key and distribution as value
  const distributionsMap = new Map<string, Distribution>();
  distributions.forEach((distribution: Distribution) => {
    distributionsMap.set(distribution.kid, distribution);
  });

  const vippsPending = vipps.filter(
    (agreement: VippsAgreement) =>
      agreement.status === "PENDING" &&
      DateTime.fromISO(agreement.timestamp_created).diff(DateTime.now(), "days").days > -7,
  );
  const avtalegiroPending = avtaleGiro.filter(
    (agreement: AvtaleGiroAgreement) =>
      agreement.active === 0 &&
      agreement.cancelled === null &&
      DateTime.fromISO(agreement.created).diff(DateTime.now(), "days").days > -7,
  );
  const pendingCount = vippsPending.length + avtalegiroPending.length;

  return (
    <>
      <Head>
        <title>Gi Effektivt. | Avtaler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader hideOnScroll={false}>
        <Navbar {...navbarData} />
        <AgreementsMenu
          selected={selected}
          onChange={(selected) => setSelected(selected)}
        ></AgreementsMenu>
      </MainHeader>

      <PageContent>
        <div className={styles.container}>
          <h3 className={styles.header}>Faste avtaler</h3>

          {pendingCount >= 1 && (
            <InfoBox>
              <header>
                <Clock size={24} color={"black"} />
                {pendingCount} {pendingCount === 1 ? "avtale" : "avtaler"} bekreftes
              </header>
              <p>
                Vi har registrert {pendingCount} {pendingCount === 1 ? "ny avtale" : "nye avtaler"}{" "}
                på deg. Bankene bruker noen dager på å bekrefte opprettelse før avtalen din blir
                aktivert.
              </p>
            </InfoBox>
          )}

          {window.innerWidth > 1180 || selected === "Aktive avtaler" ? (
            <AgreementList
              title={"Aktive"}
              vipps={activeVippsAgreements}
              avtalegiro={activeAvtalegiroAgreements}
              distributions={distributionsMap}
              taxUnits={taxUnits}
              supplemental={"Dette er dine aktive betalingsavtaler du har med oss"}
              emptyString={"Vi har ikke registrert noen aktive faste donasjonsavtaler på deg."}
              expandable={true}
            />
          ) : null}

          {window.innerWidth > 1180 || selected === "Inaktive avtaler" ? (
            <AgreementList
              title={"Inaktive"}
              vipps={vipps.filter((agreement: VippsAgreement) => agreement.status !== "ACTIVE")}
              avtalegiro={avtaleGiro.filter(
                (agreement: AvtaleGiroAgreement) => agreement.cancelled !== null,
              )}
              distributions={distributionsMap}
              taxUnits={taxUnits}
              supplemental={
                "Dette er tidligere faste betalingsavtaler du har hatt med oss, som vi ikke lenger trekker deg for"
              }
              emptyString={"Vi har ikke registrert noen tidligere donasjonsavtaler på deg."}
              expandable={false}
            />
          ) : null}
        </div>
      </PageContent>
    </>
  );
});

type FetchAgreementsPageResult = {
  dashboard: Array<{ dashboard_slug?: { current?: string } }>;
  page?: Array<{ slug?: { current?: string } }>;
};

const fetchAgreementsPage = groq`
{
  "dashboard": *[_id == "dashboard"] {
    dashboard_slug {
      current
    },
  },
  "page": *[_id == "agreements"] {
    slug {
      current
    }
  }
}
`;
