import { groq } from "next-sanity";
import Head from "next/head";
import { useRouter } from "next/router";
import "react-toastify/dist/ReactToastify.css";
import { DataInfo } from "../../components/profile/details/DataInfo/DataInfo";
import { ProfileInfo } from "../../components/profile/details/ProfileInfo/ProfileInfo";
import { PageContent } from "../../components/profile/layout/PageContent/PageContent";
import { Navbar } from "../../components/profile/layout/navbar";
import { MainHeader } from "../../components/shared/layout/Header/Header";
import { getClient } from "../../lib/sanity.server";
import style from "../../styles/Profile.module.css";
import { withStaticProps } from "../../util/withStaticProps";
import { LayoutType, getAppStaticProps } from "../_app.page";
import { ProfileLayout } from "../../components/profile/layout/layout";

export async function getProfilePagePath() {
  const result = await getClient(false).fetch<FetchProfilePageResult>(fetchProfilePage);

  const dashboardSlug = result?.dashboard?.[0]?.dashboard_slug?.current;
  const slug = result?.page?.[0]?.slug?.current;

  if (!dashboardSlug || !slug) return null;

  return [dashboardSlug, slug];
}

export const ProfilePage = withStaticProps(async ({ preview }: { preview: boolean }) => {
  const appStaticProps = await getAppStaticProps({ preview, layout: LayoutType.Profile });
  const result = await getClient(preview).fetch<FetchProfilePageResult>(fetchProfilePage);

  return {
    appStaticProps,
    preview: preview,
    data: {
      result: result,
      query: fetchProfilePage,
      queryParams: {},
    },
  };
})(({ data, preview }) => {
  const router = useRouter();
  const settings = data.result.settings[0];
  const dashboard = data.result.dashboard[0];

  if (!router.isFallback && !data) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>{settings.title} | Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader hideOnScroll={false}>
        <Navbar logo={settings.logo} elements={dashboard.main_navigation} />
      </MainHeader>

      <PageContent>
        <div className={style.gridContainer}>
          <ProfileInfo />
          <DataInfo page={data.result.page} />
        </div>
      </PageContent>
    </>
  );
});

type FetchProfilePageResult = {
  settings: any[];
  page: Array<{ slug?: { current?: string }; tax?: any; data?: any }>;
  dashboard: Array<{ dashboard_slug?: { current?: string }; main_navigation: any[] }>;
};

const fetchProfilePage = groq`
{
  "settings": *[_type == "site_settings"] {
    title,
    logo,
  },
  "dashboard": *[_id == "dashboard"] {
    dashboard_slug {
      current
    },
    main_navigation[] {
      _type == 'navgroup' => {
        _type,
        _key,
        title,
        items[]->{
          title,
          "slug": page->slug.current
        },
      },
      _type != 'navgroup' => @ {
        _type,
        _key,
        title,
        "slug": page->slug.current
      },
    }
  },
  "page": *[_id == "profile"] {
    slug {
      current
    },
    tax,
    data
  },
}
`;
