import Head from "next/head";
import { DataInfo } from "../../components/profile/details/DataInfo/DataInfo";
import style from "../../styles/Profile.module.css";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/router";
import { getClient } from "../../lib/sanity.server";
import { groq } from "next-sanity";
import { PageContent } from "../../components/profile/layout/PageContent/PageContent";
import { Navbar } from "../../components/profile/layout/navbar";
import { ProfileInfo } from "../../components/profile/details/ProfileInfo/ProfileInfo";
import { footerQuery } from "../../components/shared/layout/Footer/Footer";
import { MainHeader } from "../../components/shared/layout/Header/Header";
import { widgetQuery } from "../../_queries";
import { withStaticProps } from "../../util/withStaticProps";
import { LayoutType, getAppStaticProps } from "../_app.page";

export async function getProfilePagePath() {
  const result = await getClient(false).fetch<FetchProfilePageResult>(fetchProfilePage);

  const dashboardSlug = result?.dashboard?.[0]?.dashboard_slug?.current;
  const slug = result?.page?.[0]?.slug?.current;

  if (!dashboardSlug || !slug) return null;

  return [dashboardSlug, slug];
}

export const ProfilePage = withStaticProps(async ({ preview }: { preview: boolean }) => {
  const appStaticProps = await getAppStaticProps({
    layout: LayoutType.Profile,
  });
  const result = await getClient(preview).fetch<FetchProfilePageResult>(fetchProfilePage);

  return {
    appStaticProps,
    preview: preview,
    data: {
      result: result,
      query: fetchProfilePage,
      queryParams: {},
    },
  };
})(({ data, preview }) => {
  const router = useRouter();
  const settings = data.result.settings[0];

  if (!router.isFallback && !data) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Gi Effektivt. | Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader hideOnScroll={false}>
        <Navbar logo={settings.logo} />
      </MainHeader>

      <PageContent>
        <div className={style.gridContainer}>
          <ProfileInfo />
          <DataInfo data={data.result.page} />
        </div>
      </PageContent>
    </>
  );
});

type FetchProfilePageResult = {
  settings: any[];
  page: Array<{ slug?: { current?: string }; tax?: any; data?: any }>;
  dashboard: Array<{ dashboard_slug?: { current?: string } }>;
};

const fetchProfilePage = groq`
{
  "settings": *[_type == "site_settings"] {
    logo,
  },
  "dashboard": *[_type == "dashboard"] {
    dashboard_slug {
      current
    }
  },
  "page": *[_type == "profile"] {
    slug {
      current
    },
    tax,
    data
  },
  ${footerQuery}
  ${widgetQuery}
}
`;
