import Head from "next/head";
import "react-toastify/dist/ReactToastify.css";
import { linksContentQuery, useAnonymousVippsAgreement, widgetQuery } from "../../_queries";
import styles from "../../styles/Agreements.module.css";
import { PageContent } from "../../components/profile/layout/PageContent/PageContent";
import { getClient } from "../../lib/sanity.server";
import { groq } from "next-sanity";
import { Navbar } from "../../components/profile/layout/navbar";
import { footerQuery } from "../../components/shared/layout/Footer/Footer";
import { MainHeader } from "../../components/shared/layout/Header/Header";
import { useRouter } from "next/router";
import { withStaticProps } from "../../util/withStaticProps";
import { LayoutType, getAppStaticProps } from "../_app.page";
import { AnonymousVippsAgreement } from "../../components/profile/vipps/AnonymousVippsAgreement";
import { DateTime } from "luxon";

export async function getVippsAnonymousPagePath() {
  const result = await getClient(false).fetch<FetchVippsAnonymousPageResult>(
    fetchVippsAnonymousPage,
  );

  const dashboardSlug = result?.dashboard?.[0]?.dashboard_slug?.current;
  const slug = result?.vipps?.[0]?.anonymous_page?.slug.current;

  if (!dashboardSlug || !slug) return null;

  return [dashboardSlug, slug];
}

export const VippsAnonymousPage = withStaticProps(async ({ preview }: { preview: boolean }) => {
  const appStaticProps = await getAppStaticProps({
    layout: LayoutType.Profile,
  });
  const result = await getClient(preview).fetch<FetchVippsAnonymousPageResult>(
    fetchVippsAnonymousPage,
  );

  return {
    appStaticProps,
    preview: preview,
    data: {
      result: result,
      query: fetchVippsAnonymousPage,
      queryParams: {},
    },
  };
})(({ data, preview }) => {
  const settings = data.result.settings[0];
  const dashboard = data.result.dashboard[0];
  const router = useRouter();
  const agreementCode = router.query["agreement-code"] as string;
  const page = data.result.vipps?.[0].anonymous_page;

  if (!page) {
    return <div>404{preview ? " - Attempting to load preview" : null}</div>;
  }

  const { loading, data: agreementData, error } = useAnonymousVippsAgreement(agreementCode);

  const distribution = agreementData?.distribution;
  const agreement = agreementData?.agreement;
  const status = agreement?.status;

  return (
    <>
      <Head>
        <title>Gi Effektivt. | Anonym Vipps-avtale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader hideOnScroll={false}>
        <Navbar elements={dashboard.main_navigation} logo={settings.logo} />
      </MainHeader>

      <PageContent>
        <h3 className={styles.header}>Anonym Vipps-avtale</h3>
        <div className={styles.gridContainer}>
          <div className={styles.infoGridCell}>
            {agreement && !loading && (
              <>
                <div className={styles.infoSection}>
                  <p>
                    <strong>Sum:</strong> {agreement.amount} kr
                  </p>
                  <p>
                    <strong>Status:</strong>
                    {"  "}
                    {status === "ACTIVE" ? "Aktiv" : status === "STOPPED" ? "Avsluttet" : "Inaktiv"}
                  </p>
                </div>
                <div className={styles.infoSection}>
                  <p>
                    <strong>Opprettet:</strong>
                    {"  "}
                    {DateTime.fromJSDate(new Date(agreement.timestamp_created)).toFormat(
                      "dd.MM.yyyy",
                    )}
                  </p>
                  <p>
                    <strong>Trekkdag:</strong> Den {agreement.monthly_charge_day}. hver måned
                  </p>
                </div>
              </>
            )}
          </div>
          <div className={styles.editGridCell}>
            {/* TODO: Add proper loading and error messages */}
            {loading && <div>Loading...</div>}
            {error && <div>Error</div>}
            {status === "ACTIVE" && (
              <>
                <AnonymousVippsAgreement
                  endpoint={agreementCode}
                  inputDistribution={distribution}
                  inputSum={agreement.amount}
                  inputDate={agreement.monthly_charge_day}
                />
              </>
            )}
            {status === "STOPPED" && (
              <>
                <h5 className={styles.cellTitle}>Avtalen er avsluttet</h5>
                <p>Avtalen er avsluttet og vil ikke trekkes lenger.</p>
              </>
            )}
            {status !== "STOPPED" && status !== "ACTIVE" && (
              <>
                <h5 className={styles.cellTitle}>Avtalen er ikke aktiv</h5>
                <p>
                  Årsaken til dette kan være at avtalen ikke er aktivert enda, eller at det er noe
                  feil med avtalen.
                </p>
              </>
            )}
          </div>
        </div>
      </PageContent>
    </>
  );
});

type FetchVippsAnonymousPageResult = {
  settings: any[];
  dashboard: Array<{ dashboard_slug?: { current?: string }; main_navigation: any[] }>;
  vipps?: Array<{
    anonymous_page: Record<string, any> & {
      slug: {
        current: string;
      };
    };
  }>;
};

const fetchVippsAnonymousPage = groq`
{
  "settings": *[_type == "site_settings"] {
    logo,
    main_navigation[] {
      _type == 'navgroup' => {
        _type,
        _key,
        title,
        items[]->{
          title,
          "slug": page->slug.current
        },
      },
      _type != 'navgroup' => @ {
        _type,
        _key,
        title,
        "slug": page->slug.current
      },
    }
  },
  "dashboard": *[_id == "dashboard"] {
    dashboard_slug {
      current
    },
    main_navigation[] {
      _type == 'navgroup' => {
        _type,
        _key,
        title,
        items[]->{
          title,
          "slug": page->slug.current
        },
      },
      _type != 'navgroup' => @ {
        _type,
        _key,
        title,
        "slug": page->slug.current
      },
    }
  },
  ${widgetQuery}
  ${footerQuery}
  "vipps": *[_id == "vipps"] {
    anonymous_page->{
      slug {
        current
      },
      header {
        ...,
        seoImage{
          asset->
        },
        ${linksContentQuery}
      },
      content,
    }
  }
}
`;
